language: python
python:
  - "3.5"
sudo: false

# Setup miniconda
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME/miniconda"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION matplotlib jupyter scipy numpy pandas pytest coverage

# install dependencies
install:
  - source activate test-environment
  - pip install codecov
  - pip install --only-binary=shapely shapely
  - python setup.py develop

# run tests
script: 
  - coverage run --source nept -m py.test

# coverage tests
after_success:
  - codecov
